spring:
  application:
    name: service-registry

  cloud:
    config:
      uri: http://localhost:8888   # Config Server URL

  config:
    import: "configserver:"

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG
