version: '3'
services:
  service-registry:
    image: ayush4857/service-registry
    ports:
      - "8761:8761"
    networks:
      - app-network

  api-gateway:
    image: ayush4857/api-gateway
    ports:
      - "5555:5555"
    depends_on:
      - service-registry
    networks:
      - app-network

  auth-service:
    image: ayush4857/auth-service
    ports:
      - "1122:1122"
    depends_on:
      - service-registry
    networks:
      - app-network

  user-service:
    image: ayush4857/user-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
