spring:
  application:
    name: user-service

  cloud:
    config:
      uri: http://localhost:8888

  config:
    import: "configserver:"

management:
  endpoints:
    web:
      exposure:
        include: '*'   # this exposes all actuator endpoints
  endpoint:
    health:
      show-details: always   # optional, shows detailed health info

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG

