spring:
  application:
    name: user-service

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka  # <-- changed from localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info
